"""fix address primary key, identity and user_id index

The original `user_address` migration declared `id` as a bare Integer with no
PrimaryKeyConstraint, so Postgres created the table with no primary key and no
sequence. `id` was therefore NOT NULL with nothing to fill it, and every insert
failed with a not-null violation — the table was unusable.

The model has always declared `primary_key=True`, so this brings the database
in line with the model rather than the other way round.

Also adds an index on user_id: every address query filters by it, since
addresses are only ever read in the context of one user.

Revision ID: a1c4e07b92d3
Revises: fc7eba5e95fb
Create Date: 2026-08-16

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1c4e07b92d3"
down_revision: Union[str, Sequence[str], None] = "fc7eba5e95fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Primary key first: an identity column does not require one, but every row
    # here needs a stable unique handle for PATCH and DELETE to address.
    op.create_primary_key("address_pkey", "address", ["id"])

    # GENERATED BY DEFAULT, not ALWAYS, so an explicit id can still be supplied
    # — useful for fixtures and data imports. There is no Alembic op for adding
    # identity to an existing column, hence raw SQL.
    op.execute("ALTER TABLE address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

    op.create_index("ix_address_user_id", "address", ["user_id"])


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_address_user_id", table_name="address")
    op.execute("ALTER TABLE address ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.drop_constraint("address_pkey", "address", type_="primary")
