"""create orders, status history, outbox, processed events

Revision ID: c3a91d5f7e02
Revises:
Create Date: 2026-08-21

The first revision for order_db. Hand-written rather than autogenerated, for the
reason recorded in MIGRATIONS.md §5: autogenerate has nothing to diff against on
an empty database, and would miss the CHECK constraints and the partial index on
`outbox` in any case.

Four tables, and only one of them is the order:


* `orders` — the agreement, almost entirely snapshots.
* `order_status_history` — how it got to where it is.
* `outbox` — events waiting for the relay. Created now, before anything is ever
  published, because retrofitting it means unpicking every publisher from the
  transaction it should have been in.
* `processed_events` — the deduplication table every consumer will write to.
  Empty until the first Kafka handler lands; created now for the same reason.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c3a91d5f7e02"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


STATUSES = (
    "created",
    "quoted",
    "payment_pending",
    "confirmed",
    "searching_partner",
    "partner_assigned",
    "picked_up",
    "in_transit",
    "delivered",
    "settled",
    "cancelled",
)
STATUS_LIST = ", ".join(f"'{status}'" for status in STATUSES)


def _address_columns(prefix: str) -> list[sa.Column]:
    """The nine columns that snapshot one end of the trip.

    Written as a helper because pickup and drop must not drift apart — a
    difference of one nullable between them is the kind of thing that surfaces
    only when a real order fails to insert.
    """
    return [
        sa.Column(f"{prefix}_line1", sa.Text(), nullable=False),
        sa.Column(f"{prefix}_line2", sa.Text(), nullable=True),
        sa.Column(f"{prefix}_city", sa.String(length=255), nullable=False),
        sa.Column(f"{prefix}_pin_code", sa.String(length=6), nullable=False),
        sa.Column(f"{prefix}_latitude", sa.Numeric(9, 6), nullable=False),
        sa.Column(f"{prefix}_longitude", sa.Numeric(9, 6), nullable=False),
        sa.Column(f"{prefix}_contact_name", sa.String(length=100), nullable=False),
        sa.Column(f"{prefix}_contact_phone", sa.String(length=10), nullable=False),
    ]


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("public_ref", sa.String(length=12), nullable=False),
        sa.Column("customer_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="created",
        ),
        *_address_columns("pickup"),
        *_address_columns("drop"),
        sa.Column("package_weight_kg", sa.Numeric(8, 2), nullable=False),
        sa.Column("package_description", sa.Text(), nullable=True),
        sa.Column("vehicle_type", sa.String(length=20), nullable=False),
        sa.Column("distance_km", sa.Numeric(8, 2), nullable=True),
        sa.Column("quoted_amount", sa.Numeric(10, 2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="INR"),
        sa.Column("quote_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("payment_intent_id", sa.String(length=64), nullable=True),
        sa.Column("partner_id", sa.BigInteger(), nullable=True),
        sa.Column("partner_name", sa.String(length=100), nullable=True),
        sa.Column("partner_phone", sa.String(length=10), nullable=True),
        sa.Column("vehicle_number", sa.String(length=20), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancellation_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_orders"),
        sa.UniqueConstraint("public_ref", name="uq_orders_public_ref"),
        # The constraint that makes a retried "Confirm" tap safe under a race,
        # not merely under a sequence.
        sa.UniqueConstraint(
            "customer_id", "idempotency_key", name="uq_orders_idempotency"
        ),
        sa.CheckConstraint(f"status IN ({STATUS_LIST})", name="ck_orders_status"),
        sa.CheckConstraint("package_weight_kg > 0", name="ck_orders_weight_positive"),
        sa.CheckConstraint(
            "pickup_latitude BETWEEN -90 AND 90 AND drop_latitude BETWEEN -90 AND 90",
            name="ck_orders_latitude_range",
        ),
        sa.CheckConstraint(
            "pickup_longitude BETWEEN -180 AND 180"
            " AND drop_longitude BETWEEN -180 AND 180",
            name="ck_orders_longitude_range",
        ),
    )
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"])
    op.create_index("ix_orders_partner_id", "orders", ["partner_id"])
    # The customer's order list: the most frequent read in the app.
    op.create_index(
        "ix_orders_customer_recent", "orders", ["customer_id", "created_at"]
    )

    op.create_table(
        "order_status_history",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(length=20), nullable=True),
        sa.Column("to_status", sa.String(length=20), nullable=False),
        sa.Column("caused_by_event_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=20), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_order_status_history"),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name="fk_order_status_history_order"
        ),
    )
    op.create_index("ix_order_status_history_order_id", "order_status_history", ["order_id"])

    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name="pk_outbox"),
        # The unique constraint is what stops a retried write queueing the same
        # event twice.
        sa.UniqueConstraint("event_id", name="uq_outbox_event_id"),
    )
    # Partial: the relay only ever asks for unpublished rows, so this stays the
    # same speed after a million orders as on day one.
    op.create_index(
        "ix_outbox_unpublished",
        "outbox",
        ["id"],
        postgresql_where=sa.text("published_at IS NULL"),
    )

    op.create_table(
        "processed_events",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("event_id", name="pk_processed_events"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("processed_events")
    op.drop_index("ix_outbox_unpublished", table_name="outbox")
    op.drop_table("outbox")
    op.drop_index("ix_order_status_history_order_id", table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index("ix_orders_customer_recent", table_name="orders")
    op.drop_index("ix_orders_partner_id", table_name="orders")
    op.drop_index("ix_orders_customer_id", table_name="orders")
    op.drop_table("orders")
