"""create partners and vehicles

Revision ID: b1f4a72c9e01
Revises:
Create Date: 2026-08-16

The first revision for partner_db. Hand-written rather than autogenerated,
because autogenerate has nothing to diff against on an empty database and would
in any case miss the CHECK constraints and the partial unique index — see
MIGRATIONS.md §5.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b1f4a72c9e01"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "partners",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("token_secret", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="offline",
        ),
        sa.Column(
            "is_verified", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.Column("current_latitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("current_longitude", sa.Numeric(9, 6), nullable=True),
        sa.Column(
            "location_updated_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "rating", sa.Numeric(2, 1), nullable=False, server_default="5.0"
        ),
        sa.Column("rating_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "is_deleted", sa.Boolean(), nullable=False, server_default="false"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        # phone is unique *and* indexed on the model, which SQLAlchemy renders
        # as one unique index rather than a constraint plus an index — see
        # ix_partners_phone below. Declaring a UniqueConstraint here as well
        # would leave the migration and the model permanently out of step, and
        # every future --autogenerate would propose "fixing" it.
        sa.UniqueConstraint("email", name="uq_partners_email"),
        sa.CheckConstraint(
            "status IN ('offline','online','on_trip','suspended')",
            name="ck_partners_status",
        ),
        sa.CheckConstraint("rating >= 0 AND rating <= 5", name="ck_partners_rating_range"),
        sa.CheckConstraint("rating_count >= 0", name="ck_partners_rating_count"),
        sa.CheckConstraint(
            "current_latitude IS NULL OR (current_latitude BETWEEN -90 AND 90)",
            name="ck_partners_latitude_range",
        ),
        sa.CheckConstraint(
            "current_longitude IS NULL OR (current_longitude BETWEEN -180 AND 180)",
            name="ck_partners_longitude_range",
        ),
    )
    op.create_index("ix_partners_phone", "partners", ["phone"], unique=True)
    # The Dispatch query in one index: status and verification first because
    # they are the selective filters, then the bounding-box columns.
    op.create_index(
        "ix_partners_availability",
        "partners",
        ["status", "is_verified", "current_latitude", "current_longitude"],
    )

    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("vehicle_type", sa.String(length=20), nullable=False),
        sa.Column("vehicle_number", sa.String(length=20), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("capacity", sa.Numeric(8, 2), nullable=False),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            server_default="pending",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["partner_id"], ["partners.id"], name="fk_vehicles_partner_id"
        ),
        sa.UniqueConstraint("vehicle_number", name="uq_vehicles_number"),
        sa.CheckConstraint(
            "vehicle_type IN ('two_wheeler','three_wheeler','mini_truck','truck')",
            name="ck_vehicles_type",
        ),
        sa.CheckConstraint(
            "status IN ('pending','inactive','active','rejected')",
            name="ck_vehicles_status",
        ),
        sa.CheckConstraint("capacity > 0", name="ck_vehicles_capacity_positive"),
    )
    op.create_index("ix_vehicles_partner_id", "vehicles", ["partner_id"])
    # "At most one active vehicle per partner", in the database rather than in
    # the service's memory. Partial, so parked vehicles are unconstrained.
    op.create_index(
        "uq_vehicles_one_active_per_partner",
        "vehicles",
        ["partner_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # vehicles first: it holds the foreign key into partners.
    op.drop_index("uq_vehicles_one_active_per_partner", table_name="vehicles")
    op.drop_index("ix_vehicles_partner_id", table_name="vehicles")
    op.drop_table("vehicles")

    op.drop_index("ix_partners_availability", table_name="partners")
    op.drop_index("ix_partners_phone", table_name="partners")
    op.drop_table("partners")
